### ISSUE TITLE
sourceMapReference 

### ISSUE THREAD

**Issue by Qin-Ti** [imvkmark/umi-demo#1]
sourceMapReference 是开启sourcemap吗

**Comment by Qin-Ti** [comment]
你这里没有嵌入 dsn吗

**Comment by imvkmark** [comment]
复制 `.sentryclirc.sample` 并重命名为 `.sentryclirc`, 根据说明来配置.

对于 `sourceMapReference` 可以根据  https://www.npmjs.com/package/@sentry/webpack-plugin  的说明

> Determines whether sentry-cli should attempt to link minified files with their corresponding maps. By default, it will match files and maps based on name, and add a Sourcemap header to each minified file for which it finds a map. Can be disabled if all minified files contain sourceMappingURL. Defaults to true.

是否允许通过 minify 的文件映射到 sourcemap , 这个便于对 minify 的文件进行反解, 找到出错的源代码的位置

**Comment by imvkmark** [comment]
我的这个demo 也是很早的时候搭建的, 建议再参考下相关版本的文档, 避免版本不一致导致的配置误差

**Comment by Qin-Ti** [comment]
想让umi2开启soucemap，还是不知道怎么配置 这几个文档都看了

**Comment by imvkmark** [comment]
> 想让umi2开启soucemap，还是不知道怎么配置 这几个文档都看了

我们要不要考虑升级 3 ...

**Comment by Qin-Ti** [comment]
老项目，牵扯太多，可能会考虑下umi4（今天作者刚发布），umi2的资料太少了  得自己填坑
